name: 'Create Release PR'
description: "Update a repository's npm package(s). Monorepo-compatible."

inputs:
  release-branch-prefix:
    description: "The prefix of the release PR branch name, to which the release's SemVer version will be appended."
    default: 'release/'
    required: true
  release-type:
    description: 'A SemVer version diff, e.g. "major", "minor", or "patch". Mutually exclusive with "release-version".'
    required: false
  release-version:
    description: 'A plain SemVer version string, specifying the version to bump to. Mutually exclusive with "release-type".'
    required: false
  artifacts-path:
    description: 'The path to the directory where this action will create its artifact files.'
    required: false
  create-draft-pr:
    default: 'draft'
    description: 'The status of the pull request when created. Allowed options are "draft" and "open"'
    required: true

runs:
  using: 'composite'
  steps:
    - id: update-packages
      shell: bash
      run: node ${{ github.action_path }}/dist/index.js
      env:
        RELEASE_TYPE: ${{ inputs.release-type }}
        RELEASE_VERSION: ${{ inputs.release-version }}
    - id: create-release-pr
      shell: bash
      run: |
        ${{ github.action_path }}/scripts/create-release-pr.sh \
          ${{ steps.update-packages.outputs.NEW_VERSION }} \
          ${{ inputs.release-branch-prefix }} \
          ${{ github.actor }} \
          ${{ inputs.create-draft-pr }} \
          ${{ inputs.artifacts-path }}
