name: "Create Release PR"
description: "Create Release Pull Request when new branch is created matching branch-prefix"
inputs:
  release-version:
    description: 'A specific version to bump to. Mutually exclusive with "release-type".'
    required: true
runs:
  using: "composite"
  steps:
    - shell: bash
      run: ${{ github.action_path }}/run.sh ${{ inputs.release-version }} ${{ github.action_path }}
