name: 'Create Monorepo Release PR'
description: 'Update the versions of monorepo packages and create a release PR.'

inputs:
  release-type:
    description: 'A SemVer version diff, e.g. "major", "minor", or "patch". Mutually exclusive with "release-version".'
    required: false
  release-version:
    description: 'A plain SemVer version string, specifying the version to bump to. Mutually exclusive with "release-type".'
    required: false

runs:
  using: 'composite'
  steps:
    - id: update-packages
      shell: bash
      run: node ${{ github.action_path }}/dist/index.js
      env:
        RELEASE_TYPE: ${{ inputs.release-type }}
        RELEASE_VERSION: ${{ inputs.release-version }}
    - id: create-release-pr
      shell: bash
      run: ${{ github.action_path }}/src/create-release-pr.sh ${{ steps.update-packages.outputs.NEW_VERSION }}
